package taglines

import (
	"math/rand"
)

var lines = []string{
	"Trust, but verify. Actually, just verify.",
	"Because tripwire --init ruined your Saturday.",
	"Watching your hosts so you don't have to.",
	"sudo make me a sandwich",
	"It's not paranoia if they're really in your /proc",
	"Who watches the watchmen? We do.",
	"Your hosts called. They said something changed.",
	"chmod 000 your worries away.",
	"Scanning hosts since you forgot to.",
	"We read your /etc so you don't have to.",
	"There's no place like 127.0.0.1",
	"Hack the planet! (But we'll notice.)",
	"rm -rf /doubt",
	"All your base(line) are belong to us.",
	"Detecting threats faster than your coffee cools.",
	"The night is dark and full of rootkits.",
	"curl -s your-infra | grep problems",
	"Have you tried turning the firewall off and on?",
	"Another day, another zero-day.",
	"Logging everything except your mistakes.",
	"In /var/log, no one can hear you scream.",
	"Security through obscurity is not a tagline.",
	"The S in IoT stands for Security.",
	"Your crontab has trust issues.",
	"Quis custodiet ipsos custodes? This tool.",
	"One does not simply walk into production.",
	"Now with 100% more paranoia.",
	"Keeping /etc/passwd boring since 2024.",
	"May your alerts be few and your patches quick.",
	"It works on my machine. That's the problem.",
	"I see dead processes.",
	"Speak friend and enter. We'll log that.",
	"You have 99 problems. We found 12 more.",
	"Making auditd feel inadequate since day one.",
	"We're not saying it was a hacker, but...",
	"Trusted by sysadmins who've been burned before.",
	"Powered by caffeine and packet captures.",
	"Where we're going, we still need firewalls.",
	"It's always DNS. Except when it's not.",
	"cat /dev/urandom | your_security_posture",
	"Because last time you said 'it's probably fine.'",
	"This is fine. (narrator: it was not fine.)",
	"Your infrastructure's designated worrier.",
	"If a port opens in the forest, we hear it.",
	"Monitoring your attack surface so you can sleep.",
	"Less exciting than Metasploit. More useful daily.",
	"Your hosts are whispering. We're listening.",
	"nmap yourself before they nmap you.",
	"Paranoid? Good. That's a feature.",
	"We put the 'no' in unauthorized.",
	"Because nobody audits at 3am voluntarily.",
	"Catching drift before it catches you.",
	"Immutable infrastructure, mutable reality.",
	"The config was coming from inside the house.",
	"grep -r 'hope' /dev/null",
	"Defense in depth, alerts in width.",
	"Your SIEM's less dramatic cousin.",
	"Less false positives than your ex.",
	"Every file you touch leaves a trace.",
	"tail -f /var/log/regret",
	"Now you see it. Now we alert on it.",
	"Patching is a lifestyle, not an event.",
	"Like having a sysadmin who never sleeps.",
	"We find what nessus missed.",
	"Entropy is not your friend.",
	"I came, I saw, I diffed.",
	"Detecting changes since before it was cool.",
	"Your compliance officer's favorite tool.",
	"ssh -o TrustNobody=yes",
	"Because post-mortems aren't fun.",
	"You can't secure what you can't see.",
	"Shift left, scan right, sleep tight.",
	"Even your .bashrc has secrets.",
	"The audit log remembers what you forgot.",
	"No CVE was harmed in this scan.",
	"Keep calm and rotate your keys.",
	"/dev/null called. It wants your alerts back.",
	"Reading /proc so you don't have nightmares.",
	"Where there's smoke, there's iptables rules.",
	"We log your logs logging logs.",
	"DNS: it's always DNS.",
	"More layers than an OSI model.",
	"Your /tmp is showing.",
	"Born to scan. Forced to alert.",
	"History | grep 'mistakes'",
	"Segfaults are just unplanned features.",
	"ping -c 1 peace-of-mind",
	"Turning coffee into security findings.",
	"0-day protection, 24/7 paranoia.",
	"Catch them red-handed, or at least red-flagged.",
	"There is no cloud. It's someone else's diff.",
	"Checksums: because feelings aren't reliable.",
	"Your .ssh directory thanks you.",
	"We make tripwire look like a hobby.",
	"Unattended upgrades, attended consequences.",
	"Don't @ me, @ your firewall.",
	"The only good port is a closed port.",
	"We've seen things you wouldn't believe.",
	"Like strace, but for your whole fleet.",
	"Making SOC analysts slightly less miserable.",
	"Unauthorized changes? Not on our watch.",
	"Your baseline called. It's disappointed.",
	"Deterministic paranoia as a service.",
	"Between us and chaos: one config file.",
	"echo 'sleep well' > /dev/null",
	"We diff, therefore we are.",
	"Warranty void if tampered with. We'll know.",
	"Some assembly required. No disassembly tolerated.",
	"chmod -R peace-of-mind /",
	"We're the reason attackers cry.",
	"Your kernel called. Something's different.",
	"Faster than a speeding CVE.",
	"Logging: because 'I swear I didn't touch it.'",
	"We scan in the shadows so you can rest.",
	"A stitch in time saves nine incidents.",
	"Security is a process. This is that process.",
	"awk '{print peace_of_mind}' your-infra",
	"Firewalls are just aggressive suggestions.",
	"The best incidents are the ones that don't happen.",
	"Sniffing packets, judging configs.",
	"404: Vulnerability Not Found. You're welcome.",
	"More alerts than your ex on Instagram.",
	"We make baselines cool. Okay, cooler.",
	"Your threat model's new best friend.",
	"Resistance is not futile. It's mandatory.",
	"SELinux: because we hate ourselves lovingly.",
	"Trust no one. Scan everyone.",
	"We put the FIM in affirmation.",
	"Containers don't fix bad configs.",
	"xkcd 327 approved.",
	"Your infrastructure has a paper trail now.",
	"More paranoid than your security team.",
	"Finding needles in your host stack.",
	"World-readable? Not for long.",
	"We don't judge your crontab. Much.",
	"exec security-monitoring --forever",
	"Where others see servers, we see suspects.",
	"Like a canary in a coal mine. Digital.",
	"diff --brief production yesterday",
	"Breaking bad (configurations) since launch.",
	"We're watching. Not in a creepy way.",
	"systemctl status peace-of-mind",
	"Your /etc/shadow's personal bodyguard.",
	"Root cause analysis before root access abuse.",
	"LGTM (Looks Good, Thoroughly Monitored).",
	"We're basically tripwire with better jokes.",
	"Scan early, scan often, sleep soundly.",
	"Hashing out your problems, one file at a time.",
	"apt-get install peace-of-mind",
	"Because 'it was like that when I got here.'",
	"Your infra's immune system.",
	"dig +short your-attack-surface",
	"We don't always scan, but when we do: always.",
	"Like Nagios, but you'll actually read the alerts.",
	"netstat -paranoia",
	"The diff that saved Christmas.",
	"Watching bits flip so you don't flip out.",
	"For when 'git blame' isn't enough.",
	"pkill -9 complacency",
	"Your SOC's silent partner.",
	"We count your open ports so you don't have to.",
	"Immutability is a lie. We'll prove it.",
	"ls -la /your/concerns",
	"Not all heroes wear capes. Some run scans.",
	"We see your drift and raise you an alert.",
	"Like a home alarm, but for /home.",
	"It compiled, shipped, and something changed.",
	"find / -name 'trouble' -type f 2>/dev/null",
	"Integrity is our middle name. Literally.",
	"Your endpoints have stories. We read them.",
	"ps aux | grep suspicious",
	"traceroute to peace of mind: 1 hop.",
	"SYN, SYN-ACK, SCAN.",
	"Better living through checksums.",
	"Ctrl+Z won't undo a breach.",
	"The filesystem is a liar. We keep receipts.",
	"Helping you sleep since your last incident.",
	"Because 'who changed that?' has an answer now.",
	"whois worried? Not you. Not anymore.",
	"We make your change management honest.",
	"chmod 700 your infrastructure.",
	"Threat hunting without the camo pants.",
	"Last login: just now. We noticed.",
	"Uptime is nice. Integrity is better.",
	"Finally, something your auditor will like.",
	"Making 'nothing happened' verifiable.",
	"Your canary in the server room.",
	"We were monitoring before it was mandatory.",
	"Compliance called. You're welcome.",
	"xargs -I{} scan {} --thoroughly",
	"Honey, I shrunk the attack surface.",
	"Less drama than your Kubernetes cluster.",
	"If it moves, we hash it.",
	"Queueing your concerns, processing your fears.",
	"man security | less (panic)",
	"We've got your six. And your port 22.",
	"journalctl -u paranoia --no-pager",
	"We read RFCs so you don't have to.",
	"Proof that someone touched your stuff.",
	"Because tripwire --init ruined your Saturday.",
}

// Random returns a random tagline.
func Random() string {
	return lines[rand.Intn(len(lines))]
}
